application: twitter-mood
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1h"

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: index.html
  upload: index.html

- url: /api/.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest